apiVersion: v1
kind: Service
metadata:
  name: standalone-service
spec:
  selector:
    app: standalone-app
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5000    # Cambiado de 80 a 5000
    targetPort: 5000  # Cambiado de 80 a 5000
