apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWU=  # "username" codificado en Base64
  password: cGFzc3dvcmQ=  # "password" codificado en Base64
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  -

 name: app
    image: busybox
    command: [ "sh", "-c", "echo Secret Username: $USERNAME; echo Secret Password: $PASSWORD; sleep 3600" ]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password